tryber/sd-014-b-project-frontend-online-store

src/App.js, src/components/Home.jsx, src/pages/SwitcherPage.jsx
=> impl: page SwitcherPage and Home Component

public/index.html, src/App.js, src/Components/TelaCarrinhoCompras.jsx, src/Components/TelaPrincipal.jsx
também foi alterado o index.html (language) para pt-br para o google parar de pedir a tradução
=> [Grupo 17] Requisito 3

src/components/Home.jsx
=> refatorando o codigo para passar nos testes

src/App.js, src/pages/ProductListing.jsx
Teste pra saber o que eu tô fazendo e não fazer besteira
=> Grupo 8 - Requisito 2

package-lock.json, src/services/api.js
Implementa requisições na API do Mercado Livre
=> [Grupo 7] Requisito 1

src/App.js, src/pages/Home.jsx
Implementa página home com mensagem inicial
=> [Grupo 7] Requisito 2

package-lock.json, src/App.js, src/pages/Home.jsx
cria diretório pages, componente Home e adiciona Route, Switch e BrowserRouter ao App.
=> [GRUPO 26] Requisito 02

package-lock.json, src/App.js, src/pages/Cart.jsx, src/pages/Home.jsx
cria componente Cart, seta Link no Home, seta Route no App
=> [GRUPO 26] Requisito 03

src/App.js, src/services/api.js
Faz a implementação das funções getCategories e getProductsFromCategoryAndQuery do requisito 1.
=> [ Requisito 1 ] Impl: getCategories e getProductsFromCategoryAndQuery

src/components/FilterCategories.js, src/pages/Home.js
Main group 3 requisito 4 - Bel-Mayara-Jean-Danilo
=> Main group 3 requisito 4 - Bel-Mayara-Jean-Danilo

src/pages/Nav.jsx, src/pages/ProductList.jsx
apenas migrando o "export default" para a declaração da class.
=> [grupo 12] ajustando semantica do NAV

src/pages/ProductList.jsx
mudança boba, mas acho q deu uma automatizada na interação com o usuario, o que acham?
=> [grupo 12] Input de pesquisa dinamico

src/components/Categories.jsx, src/components/ProductCard.jsx, src/components/ProductDetails.jsx, src/components/SearchBar.jsx, src/pages/Home.jsx, src/pages/ShoppingCart.jsx
Função que permite adicionar produtos ao carrinho foi implementada.
=> Main group 08 requisito 08

src/components/Card.js, src/pages/Home.jsx
=> [Grupo 07] Requisito 6

src/Components/Categories/Categories.jsx, src/pages/Home.jsx
Implementa função de filtrar a busca por categoria
=> [ Main Group 19 ] Requisito 6

src/pages/ButtonQuantity.jsx, src/pages/Cart.jsx
- Cria componente ButtonQuantity
=> [Grupo 12] Requisito 10

src/components/ProductDetails.jsx, src/components/Rating.jsx
parece correto, mas o teste nao passa por causa do bug no requisito 9, creio eu
=> [Grupo 8] - Requisito 11

src/components/Card.js, src/components/CartProduct.jsx, src/components/ProductCatalog.js, src/pages/ShoppingCart.jsx
… o valor total e permitir a manipulação da sua quantidade
=> [Main group 7] Requisito 10

src/App.js, src/Components/CardCarrinhoCompras.jsx, src/Components/CardCategoriaTelaPrincipal.jsx, src/Components/CardProdutoTelaPrincipal.jsx, src/Components/TelaCarrinhoCompras.jsx, src/Components/TelaPrincipal.jsx, src/Components/TelaSaibaMais.jsx, src/__tests__/requirement10.test.js, src/__tests__/requirement11.test.js, src/__tests__/requirement12.test.js, src/__tests__/requirement13.test.js, src/__tests__/requirement14.test.js, src/__tests__/requirement15.test.js
Realizado algumas alterações no código para melhorar a legibilidade, passou em testes do requisito 1 ao 9.
foi colocado o ".skip" nos describe dos testes 10 ao 15 que serve para pular estes testes. (porque ainda não fizemos)
Estes ".skip" devem ser removidos para os testes voltarem a funcionar normalmente.
Vamos verificar juntos na reunião (DM) se a implementação vai ou não ser realizada.
=> Main group 17 codigo refatorado

src/components/CartItem.jsx, src/components/ProductCard.jsx, src/components/ProductDetails.jsx, src/pages/Home.jsx, src/pages/ShoppingCart.jsx, src/services/product.service.js
Além do requisito 10, também foi corrigido um bug onde o produto era adicionado duas vezes quando adicionado pela tela de descrição do produto.
=> Requisito 10 - Adição e remoção de produtos no carrinho.

src/App.js, src/Components/ProductCard/ProductCard.jsx, src/pages/Home.jsx, src/pages/ProductDetails.jsx
Obs: Tinha abrido o PR errado!
O requisito está passando no teste, só falta lapidar o código!
=> [ Main Group 19 ] Requisito 7

src/pages/CartPage.jsx, src/pages/Home.jsx
Faz com que o botão de adicionar ao carrinho jogue os produtos na localStorage ao invés de passar para a página de carrinhos via state do prop.
=> [Main Group 28] Requisito 8: correção de bug

src/App.js, src/components/AddCart.jsx, src/components/PaymentForm.jsx, src/components/Product/Product.jsx, src/components/UserData.jsx, src/pages/Cart.jsx, src/pages/Checkout.jsx, src/pages/ProductDetails.jsx
Falta lint. E nomes dos input do dado do user
=> [Grupo 12] Requisito 12

package-lock.json, package.json, src/App.css, src/App.js, src/components/CartItem.jsx, src/components/ListCategories.jsx, src/components/ProductCard.jsx, src/index.css, src/index.js, src/pages/Cart.jsx, src/pages/Home.jsx
CSS da aplicação realizado, porém ficou pendente para resolver alguns bugs da página cart para ser resolvidos posteriormente
=> [Grupo 26] - implementação css
